001/sol: 001/sol.hs
	ghc -o 001/sol --make 001/sol.hs
002/sol: 002/sol.hs
	ghc -o 002/sol --make 002/sol.hs
003/sol: 003/sol.hs
	ghc -o 003/sol --make 003/sol.hs
004/sol: 004/sol.hs
	ghc -o 004/sol --make 004/sol.hs
005/sol: 005/sol.hs
	ghc -o 005/sol --make 005/sol.hs
006/sol: 006/sol.hs
	ghc -o 006/sol --make 006/sol.hs
007/sol: 007/sol.hs
	ghc -o 007/sol --make 007/sol.hs
015/sol: 015/sol.hs
	ghc -o 015/sol --make 015/sol.hs
