#!/usr/bin/env sh
echo "Download Speed" $(bmon -o ascii:quitafter=2 -penp3s0 | tail -n1 | sed "s/[ ]\+/\t/g" | cut -f3)
ls -lht db/*.sqlite3  | head -n20
echo ""
ls -lhS db/*.log | head -n10 
echo "Started:  " $(ls db/*.log | wc -l)
echo "Finished: " $(tail db/*.log | grep "FINISHED PULLING FULLDATA" | wc -l)
echo "Total DB size: " $(du -h db | cut  -f1)
bytes=$(grep "Finished Download" db/*.log | cut -d' ' -f11 | paste -sd+ | bc)
echo "Total Downloaded: $bytes bytes, " $(echo "$bytes/1024./1024/1024"|bc) "GB"
