/*  PixelGUI_Linkdef.h
 *  	Author: Caleb Fangmeier
 * 		contact: cfangmeier@hotmail.com
 * 		date: Wed May 30 17:42:35 CDT 2012
 * 	
 * 		This class is required by rootcint to create all of the necessary
 * 		libraries that g++ will require to compile the gui. List all classes
 * 		here that are being used by PixelGUI.
 *  	AUTOGENERATED BY: ./configure
 */

	#pragma link C++ class PixelGUI;
	#pragma link C++ class TabSelectionWindow;
	#pragma link C++ class AnalysisSelectionWindow;
	#pragma link C++ class SaveSelectionWindow;
	#pragma link C++ class PixelTab;
	#pragma link C++ class anaPixelTree;
	#pragma link C++ class anaPixelTab;
	#pragma link C++ class PixelTabMacroRunner;
	#pragma link C++ class TGCommandFrame;
	#pragma link C++ class anaPixelTabBadEdges;
	#pragma link C++ class LowROCOccupancies;
	#pragma link C++ class DigiModuleMap;
	#pragma link C++ class DigiROCMap;
	#pragma link C++ class ROCEffTab;
	#pragma link C++ class PChemTab;
	#pragma link C++ class PixelTabChargeDistribution;
	#pragma link C++ class TabX;
	#pragma link C++ class kShortTab;
	#pragma link C++ class LumiblockTab;
	#pragma link C++ class OccEventTab;
	#pragma link C++ class OccTab;
	#pragma link C++ class TkPerEventTab;
	#pragma link C++ class PrimaryVertexTab;
	#pragma link C++ class TrackMomentumTab;
	#pragma link C++ class PixelTabSizeDistribution;
	#pragma link C++ class TriggerTab;
